#!/bin/bash

######HELP#########
usage="$(basename "$0") [-help] -- Documentation for image-resizer!

how to use:

    1)run (./resize --install) to install imagemagick
    2)copy your images in a empty folder and select that folder
    3)there will be some bug it will fix in next update"
install="$(basename "$0") [-install] -- sudo apt install imagemagick!" 
install2="$(basename "$0") [-cfg_yad] -- sudo apt install imagemagick!"   
seed=42
while getopts ':hs:' option; do
  case "$option" in
    h) yad --text-info --filename="help.txt" --title='help!' --width="500" --height="600" --window-icon=icon.png
       exit;;
    s) sudo apt install imagemagick
    sudo apt install yad
       exit
       ;;
  esac
done
shift $((OPTIND - 1))



########WARNING#################
if ! which convert > /dev/null; then
   zenity --warning --text="imagemagick is not installed" --window-icon=icon.png
   zenity --question --text="do you want to install imagemagick ?" --window-icon=icon.png
   case $? in
         0)
                x-terminal-emulator -e sudo apt install yad
;;
         1)
                exit;;
                
        -1)
                zenity --warning --text="Unexpected occured!" --title='Warning!' --window-icon=icon.png
                exit;;
esac
   sleep 1s;
   exit
fi
if ! which yad > /dev/null; then
   zenity --warning --text="yad is not installed" --window-icon=icon.png
   zenity --question --text="do yo want to install yad ?" --window-icon=icon.png
      case $? in
         0)
                x-terminal-emulator -e sudo apt install yad
;;
         1)
                exit;;
                
        -1)
                zenity --warning --text="Unexpected occured!" --title='Warning!' --window-icon=icon.png
                exit;;
esac
   sleep 1s;
   exit
fi
echo "image-resizer-V.2.1.dev"
echo "created by sreeranj"
################WELCOME############################
yad --window-icon=icon.png --image=icon.png --info --title='Welcome' --text='Welcome to Image Resizer 2.1' --width="400" --height="100" --text-align=CENTER --fixed --image-on-top --button="Help":"yad --text-info --filename="help.txt" --title='help!' --width="500" --height="600" --window-icon=icon.png" --button="Ok"
exval=$?
case $exval in
   1) echo "You pressed Cancel";;
   0) echo "You pressed OK";;
   252) exit;;
esac

(
echo "# Image-Resizer." ; sleep 2

echo "100"
echo "# Started." ; sleep 2
) |
yad --progress \
  --title="Staring project" \
  --window-icon=icon.png\
  --text="starting." \
  --percentage=0 \
  --auto-close \
  --auto-kill\
  --width="600" --height="100"

(( $? != 0 )) && yad --error --text="Error in yad command." --title='error' --window-icon=icon.png
############INPUT###################################

FILE=`yad --file-selection --directory --title="Choose the file having images" --window-icon=icon.png --widht="700" --height="900"`
case $? in
         0)
                echo "\"$FILE\" selected.";;
         1)
                yad --warning --text="No file selected" --title='Warning!' --window-icon=icon.png
                exit;;
        -1)
                yad --warning --text="Unexpected occured!" --title='Warning!' --window-icon=icon.png
                exit;;
esac
WIDTH=`yad --entry --entry-text="100" --text="Enter width" --title='Entry' --window-icon=icon.png`
case $? in
         0)
                echo "$WIDTH";;
         1)
                yad --warning --text="No text entered" --title='Warning!' --window-icon=icon.png
                exit;;
        -1)
                yad --warning --text="Unexpected occured!" --title='Warning!' --window-icon=icon.png
                exit;;
esac
HEIGHT=`yad --entry --entry-text="100" --text="Enter height" --title='Entry' --window-icon=icon.png`
echo "$HEIGHT"
case $? in
         0)
                echo "$HEIGHT";;
         1)
                yad --warning --text="No text entered" --title='Warning!' --window-icon=icon.png 
                exit;;
        -1)
                yad --warning --text="Unexpected occured!" --title='Warning!' --window-icon=icon.png
                exit;;
esac
FORMATE=`yad --entry --entry-text="" --text="Convert image formate" --title='Entry' --window-icon=icon.png`
echo $FORMATE
case $? in
         0)
                echo "$FORMATE.";;
         1)
                yad --warning --text="No text entered" --title='Warning!' --window-icon=icon.png
                exit;;
        -1)
                yad --warning --text="Unexpected occured!" --title='Warning!' --window-icon=icon.png
                exit;;
esac
###############PROCESSING###############################
if [ -d "$PWD/output" ] 
then
    echo "Directory exists." 
else
    mkdir output
fi
cd output
touch generated.txt
echo "resized using image-resizer2 by sreeranj" >> generated.txt
r=$RANDOM
mkdir $r
cd $r
if [[ "$FORMATE" = "jpg" ]]; then
    SCALE=`yad --scale --text="compression value" --value="100" --min-value="0" --max-value="100" --step="100" --title='slider' --window-icon=icon.png`
else
    convert $FILE/* -resize $WIDTHx$HEIGHT resized-0.$FORMATE
    (
    echo "# resizing..." ; sleep 2
    echo "50"
    echo "# resizing..." ; sleep 2
    echo "100"
    echo "# resized" ; sleep 1
    
    ) |
    yad --progress \
      --title="resizing" \
      --window-icon=icon.png\
      --text="Image Resizer." \
      --percentage=0 \
      --auto-close \
      --auto-kill\
      --width="600" --height="100"
  (( $? != 0 )) && yad --error --text="Error in yad command." --title='error' --window-icon=icon.png
    yad --info --text="image resized successfully" --title='Finsihed!' --window-icon=icon.png
    notify-send -t 100 "Finished!" "image save in $PWD"
    exit
fi
convert $FILE/* -resize $WIDTHx$HEIGHT -quality $SCALE resized-0.$FORMATE
(
echo "# resizing..." ; sleep 2
echo "50"
echo "# resizing..." ; sleep 2
echo "100"
echo "# resized" ; sleep 1
    
) |
yad --progress \--title="resizing" \
  --text="Image Resizer." \
  --window-icon=icon.png\
  --percentage=0 \
  --auto-close \
  --auto-kill\
  --width="600" --height="100"
  (( $? != 0 )) && yad --error --text="Error in yad command." --title='error' --window-icon=icon.png
#####################OUTPUT############################
yad --info --text="image resized successfully" --title='Finsihed!' --window-icon=icon.png
notify-send -t 100 "Finished!" "image save in $PWD"
$SHELL
